/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Room_namePlayer_nameRouteImport } from './routes/$room_name.$player_name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Room_namePlayer_nameRoute = Room_namePlayer_nameRouteImport.update({
  id: '/$room_name/$player_name',
  path: '/$room_name/$player_name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$room_name/$player_name': typeof Room_namePlayer_nameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$room_name/$player_name': typeof Room_namePlayer_nameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$room_name/$player_name': typeof Room_namePlayer_nameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$room_name/$player_name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$room_name/$player_name'
  id: '__root__' | '/' | '/$room_name/$player_name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Room_namePlayer_nameRoute: typeof Room_namePlayer_nameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$room_name/$player_name': {
      id: '/$room_name/$player_name'
      path: '/$room_name/$player_name'
      fullPath: '/$room_name/$player_name'
      preLoaderRoute: typeof Room_namePlayer_nameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Room_namePlayer_nameRoute: Room_namePlayer_nameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
